substitutions:
  devicename: "stromleser"
esphome:
  name: ${devicename}
  name_add_mac_suffix: false
  friendly_name: ${devicename}
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
api:
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename} hotspot"
    password: "stromleser"
captive_portal:
logger:
  level: INFO
  baud_rate: 0
sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
# Example
packages:
  # pin: !include utils/pin.yml
  interaction: !include utils/interaction.yml
  meter: !include meters/landis_gyr_e320.yml
